name: playground

test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 10

plugins:
  - name: foundry
  - name: alchemy
  - name: optimism
  - name: arbitrum
  - name: base

foundry:
  fork:
    ethereum:
      mainnet:
        upstream_provider: node
      sepolia:
        upstream_provider: node
    base:
      mainnet:
        upstream_provider: node
      sepolia:
        upstream_provider: node
    optimism:
      mainnet:
        upstream_provider: node
      sepolia:
        upstream_provider: node
    arbitrum:
      mainnet:
        upstream_provider: alchemy
      sepolia:
        upstream_provider: alchemy

node:
  ethereum:
    mainnet:
      uri: $NETWORK_1_RPC
    sepolia:
      uri: $NETWORK_11155111_RPC
  base:
    mainnet:
      uri: $NETWORK_8453_RPC
    sepolia:
      uri: $NETWORK_84532_RPC
  arbitrum:
    mainnet:
      uri: $NETWORK_42161_RPC
    sepolia:
      uri: $NETWORK_421614_RPC
  optimism:
    mainnet:
      uri: $NETWORK_10_RPC
    sepolia:
      uri: $NETWORK_420_RPC
