name: playground

test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 10

plugins:
  - name: foundry
  - name: alchemy
  - name: optimism
  - name: arbitrum
  - name: base

foundry:
  fork:
    base:
      mainnet:
        upstream_provider: alchemy
      sepolia:
        upstream_provider: alchemy
    optimism:
      mainnet:
        upstream_provider: alchemy
      sepolia:
        upstream_provider: alchemy
    arbitrum:
      mainnet:
        upstream_provider: alchemy
      sepolia:
        upstream_provider: alchemy
